language: java
jdk: oraclejdk8
sudo: false
script:
  - ant compile test-compile
  - sbt clean coverage test
after_success: "sbt coveralls"

notifications:
  email:
    recipients:
      - nourhan.ehab@guc.edu.eg
